extra:
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/NPGMgroup
  - icon: fontawesome/brands/github
    link: https://github.com/NBChub/bgcflow
markdown_extensions:
- attr_list
nav:
- Home: index.md
- QC and Data Selection:
  - seqfu: seqfu.md
  - mash: mash.md
  - fastani: fastani.md
  - checkm: checkm.md
- Functional Annotation:
  - prokka-gbk: prokka-gbk.md
  - deeptfactor: deeptfactor.md
- Genome Mining:
  - antismash: antismash.md
  - query-bigslice: query-bigslice.md
  - bigscape: bigscape.md
  - bigslice: bigslice.md
  - arts: arts.md
  - cblaster-genome: cblaster-genome.md
  - cblaster-bgc: cblaster-bgc.md
  - gecco: gecco.md
- Phylogenomic Placement:
  - automlst-wrapper: automlst-wrapper.md
- Comparative Genomics:
  - roary: roary.md
  - eggnog-roary: eggnog-roary.md
plugins:
- search
- mkdocs-jupyter:
    execute: false
    include_source: true
    no_input: true
    show_input: false
- macros
site_name: BGCFlow Report
theme:
  custom_dir: overrides
  features:
  - navigation.tabs
  - toc.integrate
  logo: assets/bgcflow/BGCFlow_logo.svg
  name: material
  palette:
  - primary: blue
    scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - primary: blue
    scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
